version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: blog_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    networks:
      - django_network

  web:
    build: .
    environment:
      - DJANGO_SETTINGS_MODULE=your_project.settings
    command: python manage.py test
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - django_network

volumes:
  postgres_data:

networks:
  django_network:
    driver: bridge
