name: Django CI/CD Pipeline

# Workflow'un hangi eventlerde çalışacağı
on:
  push:
    branches:
      - main  # main branch'ine yapılan push işlemleri ile çalışacak
  pull_request:
    branches:
      - main  # main branch'ine yapılan pull request'lerle çalışacak

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest  # Ubuntu ortamında çalışacak

    steps:
    - name: Check out code
      uses: actions/checkout@v3  # Kodu repository'den alır

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.4'  # Python 3.9 kullanacağız

    - name: Install dependencies
      run: |
        python -m venv venv  # Sanal ortam oluştur
        venv/bin/activate  # Sanal ortamı aktifleştir
        pip install -r requirements.txt  # Gereksinimlerinizi yükler

    - name: Run tests
      run: |
        venv/bin/activate
        pytest  # Testleri çalıştırır

  # Deploy job
  deploy:
    runs-on: ubuntu-latest
    needs: build  # Bu job, build job'ı tamamlandıktan sonra çalışacak
    if: github.ref == 'refs/heads/main'  # Yalnızca main branch'ine push sonrası çalışır

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.4'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Deploy to server
      run: |
        # Deploy komutlarınızı buraya ekleyin
        echo "Deploying application"
