name: Django CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.4'

    - name: Install dependencies
      run: |
        python -m venv venv  # Create virtual environment
        source venv/bin/activate  # Activate virtual environment
        pip install --upgrade pip  # Upgrade pip to the latest version
        pip install django  # Install Django
        pip install pytest  # Install pytest
        pip install pytest-django  # Install pytest-django
        pip freeze > requirements.txt  # Freeze the installed packages into requirements.txt

    - name: Run tests
      run: |
        source venv/bin/activate  # Activate virtual environment
        pytest  # Run the tests

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.4'

    - name: Install dependencies
      run: |
        python -m venv venv  # Create virtual environment
        source venv/bin/activate  # Activate virtual environment
        pip install --upgrade pip  # Upgrade pip to the latest version
        pip freeze > requirements.txt  # Install dependencies from the frozen requirements.txt

    - name: Deploy to server
      run: |
        # Add your deployment commands here, for example:
        echo "Deploying application"
        # e.g., SSH into the server, pull the latest code, install dependencies, restart services
        # ssh user@your-server "cd /path/to/app && git pull origin main && pip install -r requirements.txt && systemctl restart your-app-service"
