name: Django CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.4'

    - name: Install dependencies
      run: |
        python -m venv venv  # Create a virtual environment
        source venv/bin/activate  # Activate virtual environment
        pip install -r requirements.txt  # Install dependencies from requirements.txt
        pip install pytest pytest-django  # Install testing dependencies

    - name: Set DJANGO_SETTINGS_MODULE
      run: echo "DJANGO_SETTINGS_MODULE=posts.settings" >> $GITHUB_ENV  # Set settings module

    - name: Run tests
      run: |
        source venv/bin/activate  # Activate virtual environment
        pytest  # Run tests

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.4'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip freeze > requirements.txt  # Install dependencies from requirements.txt

    - name: Deploy to server
      run: |
        # Add your deployment commands here
        echo "Deploying application"
