name: Django CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.4'

    - name: Install dependencies
      run: |
        python -m venv venv  # Sanal ortam oluştur
        source venv/bin/activate  # Sanal ortamı aktifleştir
        pip install -r requirements.txt  # Gereksinimlerinizi yükler
        pip install pytest  # pytest'i yükler

    - name: Run tests
      run: |
        source venv/bin/activate  # Sanal ortamı aktifleştir
        pytest  # Testleri çalıştırır

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.4'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Deploy to server
      run: |
        # Deploy komutlarınızı buraya ekleyin
        echo "Deploying application"
