name: Django CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.4'

    - name: Install dependencies
      run: |
        python -m venv venv  # Virtual environment oluştur
        . venv/bin/activate  # Virtual environment'ı aktive et
        pip install --upgrade pip  # pip'i güncelle
        pip install django  # Django'yu kur
        pip install pytest pytest-django  # Test bağımlılıklarını kur

    - name: Set DJANGO_SETTINGS_MODULE
      run: echo "DJANGO_SETTINGS_MODULE=blog.settings" >> $GITHUB_ENV  # Django settings modülünü ayarla

    - name: Run tests
      run: |
        . venv/bin/activate  # Virtual environment'ı aktive et
        pytest  # Testleri çalıştır

    - name: Update requirements.txt
      run: |
        . venv/bin/activate  # Virtual environment'ı aktive et
        pip freeze > requirements.txt  # Mevcut bağımlılıkları requirements.txt dosyasına yaz

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.4'

    - name: Install dependencies
      run: |
        python -m venv venv  # Virtual environment oluştur
        . venv/bin/activate  # Virtual environment'ı aktive et
        pip install --upgrade pip  # pip'i güncelle
        pip freeze > requirements.txt  # Mevcut bağımlılıkları requirements.txt dosyasına yaz

    - name: Deploy to server
      run: |
        # Deployment komutlarını burada ekleyin
        echo "Deploying application"
